language: node_js

notifications:
  email: false

install: yarn --frozen-lockfile

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: build
      script: yarn build
    - stage: release
      if: (branch = stable) AND (type = push)
      script: npx semantic-release
